In [2]:
import numpy as np
import pandas as pd

In [5]:
# create a data fram :
user_data = {
    "marksA":np.random.randint( 1, 100 , 5 ),
    "marksB":np.random.randint( 1, 100 , 5 ),
    "marksC":np.random.randint( 1, 100 , 5 ),
}

In [6]:
np.random.randint( 1, 100 , 5 ),

(array([50, 60, 25,  9, 44]),)

In [7]:
df = pd.DataFrame(user_data)
print(df)

   marksA  marksB  marksC
0       1       6      90
1      78      46      91
2      48      20      22
3      37      95      17
4      44      50       6


In [8]:
df.head()

marksA  marksB  marksC
0       1       6      90
1      78      46      91
2      48      20      22
3      37      95      17
4      44      50       6

In [9]:
print(df.columns)

Index(['marksA', 'marksB', 'marksC'], dtype='object')


In [10]:
df = pd.DataFrame(user_data , dtype = 'float32')

In [11]:
print(df)

   marksA  marksB  marksC
0     1.0     6.0    90.0
1    78.0    46.0    91.0
2    48.0    20.0    22.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0


In [ ]:
# create  a csv from a data frame !!

In [12]:
df.to_csv('marks.csv')

In [14]:
my_data = pd.read_csv('marks.csv')

In [15]:
print(my_data)

   Unnamed: 0  marksA  marksB  marksC
0           0     1.0     6.0    90.0
1           1    78.0    46.0    91.0
2           2    48.0    20.0    22.0
3           3    37.0    95.0    17.0
4           4    44.0    50.0     6.0


In [17]:
my_data = pd.read_csv('marks.csv')
my_data = my_data.drop(columns=['Unnamed: 0'])
print(my_data)

   marksA  marksB  marksC
0     1.0     6.0    90.0
1    78.0    46.0    91.0
2    48.0    20.0    22.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0


In [ ]:
# basics : 2

In [18]:
my_data.describe()

marksA     marksB     marksC
count   5.000000   5.000000   5.000000
mean   41.600000  43.400000  45.200000
std    27.573538  34.129166  41.757634
min     1.000000   6.000000   6.000000
25%    37.000000  20.000000  17.000000
50%    44.000000  46.000000  22.000000
75%    48.000000  50.000000  90.000000
max    78.000000  95.000000  91.000000

In [19]:
my_data.tail()

marksA  marksB  marksC
0     1.0     6.0    90.0
1    78.0    46.0    91.0
2    48.0    20.0    22.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0

In [20]:
# accessing a row !
df.iloc[3]

marksA    37.0
marksB    95.0
marksC    17.0
Name: 3, dtype: float32

In [21]:
# Row and col :
df.iloc[3,1]

95.0

In [22]:
df.iloc[3][1]

95.0

In [24]:
idx = df.columns.get_loc('marksB')
df.iloc[3,idx]

95.0

In [25]:
idx = [df.columns.get_loc('marksB') , df.columns.get_loc('marksC')]
print(idx)
df.iloc[3,idx] # in the 3rd row we are printing for cols 1 & 2 !

[1, 2]


marksB    95.0
marksC    17.0
Name: 3, dtype: float32

In [26]:
idx = [df.columns.get_loc('marksB') , df.columns.get_loc('marksC')]
print(idx)
df.iloc[ :3,idx] # for 1st 3 rows and its cols 1 , 2 

[1, 2]


marksB  marksC
0     6.0    90.0
1    46.0    91.0
2    20.0    22.0

In [ ]:
# sort dataframe !

In [27]:
my_data

marksA  marksB  marksC
0     1.0     6.0    90.0
1    78.0    46.0    91.0
2    48.0    20.0    22.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0

In [28]:
my_data.sort_values(by=['marksA'] , ascending= True )

marksA  marksB  marksC
0     1.0     6.0    90.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0
2    48.0    20.0    22.0
1    78.0    46.0    91.0

In [29]:
my_data.sort_values(by=['marksA'] , ascending= False )

marksA  marksB  marksC
1    78.0    46.0    91.0
2    48.0    20.0    22.0
4    44.0    50.0     6.0
3    37.0    95.0    17.0
0     1.0     6.0    90.0

In [30]:
my_data.sort_values(by=['marksC', 'marksA'] , ascending= False )

marksA  marksB  marksC
1    78.0    46.0    91.0
0     1.0     6.0    90.0
2    48.0    20.0    22.0
3    37.0    95.0    17.0
4    44.0    50.0     6.0

In [32]:
data_array = my_data.values # this converts to a numpy array !!
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [34]:
print(data_array) # a numpy array !

[[ 1.  6. 90.]
 [78. 46. 91.]
 [48. 20. 22.]
 [37. 95. 17.]
 [44. 50.  6.]]


In [35]:
print(type(data_array))

<class 'numpy.ndarray'>


In [36]:
data_array.shape

(5, 3)

In [37]:
data_array[2][2]

22.0

In [38]:
# convert np arrays back to data frames !!

In [39]:
new_df = pd.DataFrame( data_array, dtype = 'int32' , columns=[ 'music' , 'hindi' , 'math'  ]  )

In [40]:
print(new_df)

   music  hindi  math
0      1      6    90
1     78     46    91
2     48     20    22
3     37     95    17
4     44     50     6


In [ ]:
# converting dataf to as csv files !!

In [42]:
new_df.to_csv('PCM.csv')

In [43]:
print(new_df)

   music  hindi  math
0      1      6    90
1     78     46    91
2     48     20    22
3     37     95    17
4     44     50     6


In [51]:
new_df.to_csv('PCM.csv' , index=False) # this removes the indexing from the actual file !!
print(new_df)

   music  hindi  math
0      1      6    90
1     78     46    91
2     48     20    22
3     37     95    17
4     44     50     6


In [54]:
pcm = pd.read_csv('PCM.csv')

In [56]:
print(pcm) # now we dont need to drop the `Unnamed:` 0 column !

   music  hindi  math
0      1      6    90
1     78     46    91
2     48     20    22
3     37     95    17
4     44     50     6
